"use strict";

let alreadyVerified = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"><style>p,h1,h2,h3,h4,h5,h6,li,ul,th,td{margin:0;padding:0;font-weight:normal;font-family:"Montserrat"}body{font-size:20px;letter-spacing:0.5px}</style><body style="max-width: 100%;margin: 0 auto; width:100%; border: 0px solid #fff;float: left;"><div style="width: 100%; height:170px;background-color: #000;text-align: center; margin-bottom:30px;"> </div><div style="max-width: 100%;width: 600px;margin:10px"><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Already Verified.</p><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Thank you for visiting Augumented Experience!</p></div></body></html>';

let linkExpired = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"><style>p,h1,h2,h3,h4,h5,h6,li,ul,th,td{margin:0;padding:0;font-weight:normal;font-family:"Montserrat"}body{font-size:20px;letter-spacing:0.5px}</style><body style="max-width: 100%;margin: 0 auto; width:100%; border: 0px solid #fff;float: left;"><div style="width: 100%; height:170px;background-color: #000;text-align: center; margin-bottom:30px;"> </div><div style="max-width: 100%;width: 600px;margin:10px"><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Link Expired.</p><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Thank you for visiting Augumented Experience!</p></div></body></html>';

let somethingWentWrong = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"><style>p,h1,h2,h3,h4,h5,h6,li,ul,th,td{margin:0;padding:0;font-weight:normal;font-family:"Montserrat"}body{font-size:20px;letter-spacing:0.5px}</style><body style="max-width: 100%;margin: 0 auto; width:100%; border: 0px solid #fff;float: left;"><div style="width: 100%; height:170px;background-color: #000;text-align: center; margin-bottom:30px;"> </div><div style="max-width: 100%;width: 600px;margin:10px"><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Something Went Wrong.</p><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Thank you for visiting Augumented Experience!</p></div></body></html>';

let successful = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"><style>p,h1,h2,h3,h4,h5,h6,li,ul,th,td{margin:0;padding:0;font-weight:normal;font-family:"Montserrat"}body{font-size:20px;letter-spacing:0.5px}</style><body style="max-width: 100%;margin: 0 auto; width:100%; border: 0px solid #fff;float: left;"><div style="width: 100%; height:170px;background-color: #000;text-align: center; margin-bottom:30px;"></div><div style="max-width: 100%;width: 600px;margin:10px"><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Your Email has been verified suceessfully.</p><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Thank you for visiting Augumented Experience!</p></div></body></html>';

let invalidEmail = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title></head><link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"><style>p,h1,h2,h3,h4,h5,h6,li,ul,th,td{margin:0;padding:0;font-weight:normal;font-family:"Montserrat"}body{font-size:20px;letter-spacing:0.5px}</style><body style="max-width: 100%;margin: 0 auto; width:100%; border: 0px solid #fff;float: left;"><div style="width: 100%; height:170px;background-color: #000;text-align: center; margin-bottom:30px;"> </div><div style="max-width: 100%;width: 600px;margin:10px"><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Invalid Email.</p><p style="padding-left:0px;color:#000;line-height: 33px;margin-top: 30px;margin-bottom: 15px;">Thank you for visiting Augumented Experience!</p></div></body></html>';

module.exports = {
    alreadyVerified: alreadyVerified,
    linkExpired: linkExpired,
    somethingWentWrong: somethingWentWrong,
    successful: successful,
    invalidEmail: invalidEmail
}
